# Site settings
title: Yulitza Carvajal
short_title: Yulitza Carvajal

url: https://yulitza.github.io/Personal-page/

description: "Gestión de proyectos con metodologías ágiles, adaptada al cambio y enfocados siempre en la satisfacción del cliente"
keywords: "gestión, metodología ágil, scrum, adaptación al cambio, enfoque, entrega oportuna"

meta_author: Yulitza Carvajal

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: ffa8f3 #80B3FF
  primary-rgb: '255,168,243' #"128,179,255"
  secondary: bd6fac
  secondary-dark: '189,111,172'

# Build settings
markdown: kramdown
permalink: pretty
