# Site settings
title: Yulitza Carvajal
short_title: Yulitza Carvajal

url: https://yulitza.github.io/Personal-page/

description: "Traducciones de todo tipo de documentos en Inglés, Español e Italiano. Servicio de traduccion presencial"
keywords: "traduccion, ingles, italiano, español, inteprete presencial"

meta_author: Maria Teresa Matteo Cassino

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: ffa8f3 #80B3FF
  primary-rgb: '255,168,243' #"128,179,255"
  secondary: bd6fac
  secondary-dark: '189,111,172'

# Build settings
markdown: kramdown
permalink: pretty
